services:
  mysql:
    image: mysql:8.4
    container_name: ezber-mysql
    environment:
      MYSQL_DATABASE: ezber_app
      MYSQL_USER: ezber
      MYSQL_PASSWORD: ezber_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
